language: node_js
node_js:
- 10.13.0


install:
  - npm install

cache:
  directories:
     - ./node_modules

before_script:
  - npm install -g @angular/cli
  - npm install


script:
  - npm run lint
  - npm run build #--prod



############ Enable in deploy only #############  
#after_success:
#  - npm install -g firebase-tools
#  - firebase deploy --only hosting --token "$FIREBASE_TOKEN"